<!--GET STARTED section-->
<div id="getStarted">
  <h1>Helping you manage and distribute the assets of your estate, so you can have peace of mind.</h1>

  <p><strong>Estater</strong> is devoted to helping families distribute estate assets in a simple, convenient, and timely way to avoid confusion, misunderstanding, and hurt feelings of beneficiaries. Get cost-effective and powerful estate management and distribution tools to help you avoid much of the drama associated with estate distribution.</p>

  <p><strong>Don't take our word for it, take it for a test drive...free for 1 week</strong></p>

  <a class="getStartedButton" href="index.php?page=signup"><p class="p1">Get Started Now</p><p class="p2">It's FREE for 1 week</p></a>

</div>


<!--HOW IT WORKS section-->
<div id="howItWorks">
  <h2>How it works</h2>
  <div class="container">
    <div class="create">
      <img class="icon" src="images/imgCreate.png" alt="'Create' image">
      <h3>Create</h3>
      <p><a href="index.php?page=signup">Sign up</a> and we'll walk you through the simple process of setting up an estate, naming an executor, and inviting your family to participate.</p>
      <img class="arrow2" src="images/arrow.png">
    </div>
    <div class="manage">
      <img class="icon" src="images/imgManage.png" alt="'Manage' image">
      <h3>Manage</h3>
      <p>Easily add all of your assets with photos and descriptions, designate beneficiaries, and let your beneficiaries request or claim assets. Make changes as often as you like.</p>
      <img class="arrow2" src="images/arrow.png">
    </div>
    <div class="distribute">
      <img class="icon" src="images/imgDistribute.png" alt="'Distribute' image">
      <h3>Distribute</h3>
      <p>When the time comes, easily distribute monetary and physical assets to your loves ones using our world-class distribution tools to avoiding confusion.</p>
    </div>
  </div>
</div>


<!--PRICING section-->
<div id="pricing">
  <h2>Plans priced to meet your needs</h2>
  <div class="container">
    <div class="standard">
      <h3 class="heading">Standard</h3>
      <p class="price">$10</p>
      <p class="basis">Per <span class="underline">Year</span></p>
      <p class="desc">Great for <strong>smaller</strong> family estates. Manage all estate assets and distribution for <strong>up to 10</strong> people.</p>
      <a class="button" href="index.php?page=standardPlan">SELECT THIS PLAN</a>
    </div>
    <div class="premium">
      <div class="blueContainer">
        <h3 class="heading">Premium</h3>
        <p class="price">$20</p>
        <p class="basis">Per <span class="underline">Year</span></p>
        <p class="desc">Perfect for <strong>larger</strong> family estates. Manage all estate assets and distribution for an <strong>unlimited</strong> number of people.</p>
        <div class="buttonContainer"><a class="button" href="index.php?page=premiumPlan">SELECT THIS PLAN</a></div>
      </div>
    </div>
    <div class="trial">
      <h3 class="heading">Trial</h3>
      <p class="price">FREE</p>
      <p class="basis">1 week</p>
      <p class="desc">Ideal for those who want to <strong>learn more</strong> and see if it's the right tool for their estate before subscribing.</p>
      <a class="button" href="index.php?page=trialPlan">SELECT THIS PLAN</a>
    </div>
  </div>
</div>


<!--FEATURES section-->
<div id="features">
  <h2>Features</h2>
  <ul class="featureList">
    <li>Proper titling and cataloging of assets</li>
    <li>Invite family members to participate</li>
    <li>Beneficiary designation</li>
    <li>Web and mobile applications</li>
    <li>Upload asset pictures</li>
    <li>List current monetary or tangible assets</li>
    <li>Write a description or notes about asset</li>
    <li>Designate executor or admin for estate</li>
    <li>Estimated Value of asset</li>
    <li>Ability to request/claim asset</li>
    <li>User dashboard</li>
    <li>Round robin voting/claiming</li>
    <li>Collaboration and communication tools</li>
    <li>Distribution reporting</li>
    <li>Document Upload</li>
    <li>eBay listing of unwanted/unclaimed assets</li>
  </ul>
</div>



<?php
//ppr($this, "THIS");
//ppr($this->model, "Model");
//echo "X ".$this->html."<br>";
//echo "Test: ".$this->model->test."<br>\n";
?>
