<!-- SignInView.phtml -->

<div class="signInBox">
<h1>Enter your account information</h1>
<form id="signInForm" name="signInForm" action="index.php?page=signin" method="POST">
  <input id="login" name="login" type="text" value="<?= request('login'); ?>" placeholder="Username or Email">
  <input id="pass_word" name="pass_word" type="password" value="" placeholder="Password">
  <input id="submitSignIn" name="submitSignIn" type="submit" value="OK">
</form> 
<h3>Don't have an account? <a href="index.php?page=signup">Sign Up!</a></h3>
</div>

<!-- end of SignInView.phtml -->